#*
#* Copyright 2021 NXP
#* Copyright 2013 Freescale Semiconductor, Inc.
#* All rights reserved.
#*
#* SPDX - License - Identifier : BSD - 3 - Clause
#*
#
# QNX build file for g2d overlay test code
#
#

PLATFORM ?= aarch64le

CC = qcc -Vgcc_nto$(PLATFORM)

TARGET := g2d_overlay_test

LDFLAGS += -L$(QNX_TARGET)/$(PLATFORM)/usr/lib/graphics/iMX8QM/
LDFLAGS +=  -lg2d -lscreen

CFLAGS += -I../os/qnx


OBJECTS += \
	g2d_overlay.o \
	gfx_screen.o

VPATH = . ../os/qnx

$(TARGET) : $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

%.o : %.c
	$(CC) $(CFLAGS) -MMD -c $< -o $@

clean:
	rm -f $(OBJECTS) $(OBJECTS:.o=.d) $(TARGET)
